'''
Contains all functions that use google maps to calculate transit-related
information between a given school and given home address
'''
import googlemaps
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

def find_best_route(home, school, travel_mode):
    '''
    Returns the json generated by google maps of the best route between 
    home and school

    Inputs:
        home: string containing address
        school: string containing address
        travel_mode: string such as 'transit', 'driving', or 'walking'

    Returns:
        google maps generated json
    '''
    gmaps = googlemaps.Client(key='AIzaSyBI1IzrUzrfNjmk3flBCg28YlcQcVVUsyE')

    # Arrival time is 9 AM Monday, April 4th. 
    directions_json = gmaps.directions(home, school, mode=travel_mode, 
        arrival_time=1459778400)
    best_route = directions_json[0]['legs'][0]

    return best_route


def get_transit_info(home, school):
    '''
    Returns the duration in minutes and the number of minutes spent walking for
    the fastest public transit route between home and school. 
    
    Inputs:
        home: string containing address
        school: string containing address

    Returns:
        string of list containing duration of trip in minutes and portion of 
            transit time spent walking in minutes
    '''
    best_route = find_best_route(str(home), str(school), 'transit')

    walking_time = 0 
    for step in best_route['steps']:
        if step['travel_mode'] == "WALKING":
            walking_time += step['duration']['value']

    duration = best_route['duration']['value']

    # returns string of list to be returned from SQL query
    return str([round(duration / 60), round(walking_time / 60)])

def get_duration(home, school):
    '''
    Inputs:
        home: string containing address
        school: string containing address

    Returns:
        transit time, integer
    '''
    best_route = find_best_route(str(home), str(school), 'transit')
    return best_route['duration']['value']